//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> SellerId { get; set; }
        public Nullable<int> RecordId { get; set; }
        public Nullable<int> ProductCount { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> SaleId { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Records Records { get; set; }
        public virtual Sales Sales { get; set; }
        public virtual Sellers Sellers { get; set; }
    }
}
