//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Records
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Records()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
        public string RecordName { get; set; }
        public string TeamdName { get; set; }
        public string PublisherName { get; set; }
        public Nullable<int> CountTracks { get; set; }
        public Nullable<int> GenreId { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public Nullable<int> RecordsCount { get; set; }
        public Nullable<int> Prodano { get; set; }
    
        public virtual Genres Genres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
