<?xml version="1.0" encoding="utf-8"?><Database Name="bd_Countries" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-FA4P8I0;Initial Catalog=bd_Countries;Integrated Security=True" SettingsObjectName="homeWork03.Properties.Settings" SettingsPropertyName="bd_CountriesConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Countries" Member="Countries">
    <Type Name="Countries">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Capital" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Population" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Area" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Continents" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>